# Blog settings
permalink: /blog/:title


# My variables
name: "idelem"
description: cool memories
google_verification: null
url: http://idelem.herokuapp.com/

# File management

gems: ['kramdown']
include: [".htaccess", "_read"]
exclude: ["README.md", "LICENSE", 'config.ru', 'Gemfile', 'Gemfile.lock', "vendor", "bin", "Procfile","todo"]



# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Rake
post:
  template: templates/_post.txt
  extension: md
page:
  template: templates/_page.txt
  extension: md
code:
  template: templates/_code.txt
  extension: md
read:
  template: templates/_read.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/

# Collections
collections:
  clips:
    output: true
    permalink: /clips/:title
  read:
    output: true
    permalink: /read/:title
